// src/lib/countryIso.ts
// Maps Transfermarkt full English country/league names to ISO 3166-1 alpha-2 codes.
// Used by FlagCDN: https://flagcdn.com/w20/{iso}.png
// Missing keys render text only (no broken image).

export const TM_COUNTRY_ISO: Record<string, string> = {
  'Afghanistan': 'af',
  'Albania': 'al',
  'Algeria': 'dz',
  'Andorra': 'ad',
  'Angola': 'ao',
  'Argentina': 'ar',
  'Armenia': 'am',
  'Australia': 'au',
  'Austria': 'at',
  'Azerbaijan': 'az',
  'Bahrain': 'bh',
  'Belarus': 'by',
  'Belgium': 'be',
  'Benin': 'bj',
  'Bolivia': 'bo',
  'Bosnia-Herzegovina': 'ba',
  'Brazil': 'br',
  'Bulgaria': 'bg',
  'Burkina Faso': 'bf',
  'Burundi': 'bi',
  'Cameroon': 'cm',
  'Canada': 'ca',
  'Cape Verde': 'cv',
  'Central African Republic': 'cf',
  'Chad': 'td',
  'Chile': 'cl',
  'China': 'cn',
  'Colombia': 'co',
  'Comoros': 'km',
  'Congo': 'cg',
  'Congo DR': 'cd',
  'Democratic Republic of Congo': 'cd',
  'Costa Rica': 'cr',
  'Croatia': 'hr',
  'Cuba': 'cu',
  'Cyprus': 'cy',
  'Czech Republic': 'cz',
  'Czechia': 'cz',
  'Denmark': 'dk',
  'Djibouti': 'dj',
  'Dominican Republic': 'do',
  'Ecuador': 'ec',
  'Egypt': 'eg',
  'El Salvador': 'sv',
  'England': 'gb-eng',
  'Equatorial Guinea': 'gq',
  'Eritrea': 'er',
  'Estonia': 'ee',
  'Ethiopia': 'et',
  'Finland': 'fi',
  'France': 'fr',
  'Gabon': 'ga',
  'Gambia': 'gm',
  'Georgia': 'ge',
  'Germany': 'de',
  'Ghana': 'gh',
  'Greece': 'gr',
  'Guatemala': 'gt',
  'Guinea': 'gn',
  'Guinea-Bissau': 'gw',
  'Haiti': 'ht',
  'Honduras': 'hn',
  'Hungary': 'hu',
  'Iceland': 'is',
  'India': 'in',
  'Indonesia': 'id',
  'Iran': 'ir',
  'Iraq': 'iq',
  'Ireland': 'ie',
  'Republic of Ireland': 'ie',
  'Israel': 'il',
  'Italy': 'it',
  'Ivory Coast': 'ci',
  "Côte d'Ivoire": 'ci',
  'Jamaica': 'jm',
  'Japan': 'jp',
  'Jordan': 'jo',
  'Kazakhstan': 'kz',
  'Kenya': 'ke',
  'Kosovo': 'xk',
  'Kuwait': 'kw',
  'Latvia': 'lv',
  'Lebanon': 'lb',
  'Liberia': 'lr',
  'Libya': 'ly',
  'Liechtenstein': 'li',
  'Lithuania': 'lt',
  'Luxembourg': 'lu',
  'North Macedonia': 'mk',
  'Madagascar': 'mg',
  'Malawi': 'mw',
  'Malaysia': 'my',
  'Mali': 'ml',
  'Malta': 'mt',
  'Mauritania': 'mr',
  'Mauritius': 'mu',
  'Mexico': 'mx',
  'Moldova': 'md',
  'Montenegro': 'me',
  'Morocco': 'ma',
  'Mozambique': 'mz',
  'Namibia': 'na',
  'Netherlands': 'nl',
  'New Zealand': 'nz',
  'Nicaragua': 'ni',
  'Niger': 'ne',
  'Nigeria': 'ng',
  'Northern Ireland': 'gb-nir',
  'Norway': 'no',
  'Oman': 'om',
  'Pakistan': 'pk',
  'Palestine': 'ps',
  'Panama': 'pa',
  'Paraguay': 'py',
  'Peru': 'pe',
  'Philippines': 'ph',
  'Poland': 'pl',
  'Portugal': 'pt',
  'Qatar': 'qa',
  'Romania': 'ro',
  'Russia': 'ru',
  'Rwanda': 'rw',
  'Saudi Arabia': 'sa',
  'Scotland': 'gb-sct',
  'Senegal': 'sn',
  'Serbia': 'rs',
  'Sierra Leone': 'sl',
  'Slovakia': 'sk',
  'Slovenia': 'si',
  'Somalia': 'so',
  'South Africa': 'za',
  'South Korea': 'kr',
  'South Sudan': 'ss',
  'Spain': 'es',
  'Sudan': 'sd',
  'Sweden': 'se',
  'Switzerland': 'ch',
  'Syria': 'sy',
  'Tanzania': 'tz',
  'Thailand': 'th',
  'Togo': 'tg',
  'Trinidad and Tobago': 'tt',
  'Tunisia': 'tn',
  'Turkey': 'tr',
  'Türkiye': 'tr',
  'Uganda': 'ug',
  'Ukraine': 'ua',
  'United Arab Emirates': 'ae',
  'United States': 'us',
  'Uruguay': 'uy',
  'Uzbekistan': 'uz',
  'Venezuela': 've',
  'Vietnam': 'vn',
  'Wales': 'gb-wls',
  'Yemen': 'ye',
  'Zambia': 'zm',
  'Zimbabwe': 'zw',
}

// Maps Transfermarkt league name strings to the country ISO code for its flag.
// Keys must match exactly what TM scrapes into the `league` column.
export const LEAGUE_ISO: Record<string, string> = {
  // England
  'Premier League': 'gb-eng',
  'Championship': 'gb-eng',
  'League One': 'gb-eng',
  'League Two': 'gb-eng',
  // Germany
  'Bundesliga': 'de',
  '2. Bundesliga': 'de',
  '3. Liga': 'de',
  // Spain
  'LaLiga': 'es',
  'La Liga': 'es',
  'LaLiga2': 'es',
  'Segunda División': 'es',
  // Italy
  'Serie A': 'it',
  'Serie B': 'it',
  // France
  'Ligue 1': 'fr',
  'Ligue 2': 'fr',
  // Portugal
  'Primeira Liga': 'pt',
  'Liga Portugal': 'pt',
  'Liga Portugal 2': 'pt',
  // Netherlands
  'Eredivisie': 'nl',
  'Eerste Divisie': 'nl',
  // Belgium
  'Belgian Pro League': 'be',
  'First Division A': 'be',
  // Turkey
  'Süper Lig': 'tr',
  'Super Lig': 'tr',
  'TFF First League': 'tr',
  // Russia
  'Russian Premier League': 'ru',
  'Premier League Russia': 'ru',
  // Ukraine
  'Ukrainian Premier League': 'ua',
  // Greece
  'Super League Greece': 'gr',
  'Super League 2': 'gr',
  // Scotland
  'Scottish Premiership': 'gb-sct',
  // Switzerland
  'Swiss Super League': 'ch',
  // Austria
  'Austrian Football Bundesliga': 'at',
  'Bundesliga Austria': 'at',
  // Czech Republic
  'Czech First League': 'cz',
  'Fortuna liga': 'cz',
  // Poland
  'Ekstraklasa': 'pl',
  // Romania
  'Liga I': 'ro',
  'Romanian Liga I': 'ro',
  // Hungary
  'OTP Bank Liga': 'hu',
  'Nemzeti Bajnokság I': 'hu',
  // Croatia
  'Hrvatska nogometna liga': 'hr',
  'HNL': 'hr',
  // Serbia
  'Serbian SuperLiga': 'rs',
  'Super liga Srbije': 'rs',
  // Israel
  "Israeli Premier League": 'il',
  "Ligat ha'Al": 'il',
  'National League Israel': 'il',
  // Denmark
  'Superligaen': 'dk',
  // Sweden
  'Allsvenskan': 'se',
  // Norway
  'Eliteserien': 'no',
  // Argentina
  "Argentine Primera División": 'ar',
  'Primera División': 'ar',
  'Primera Nacional': 'ar',
  // Brazil
  'Série A': 'br',
  'Serie A Brazil': 'br',
  'Série B': 'br',
  // Uruguay
  'Liga AUF Apertura': 'uy',
  'Liga AUF Clausura': 'uy',
  'Primera División Uruguay': 'uy',
  // Colombia
  'Liga BetPlay DIMAYOR': 'co',
  'Categoría Primera A': 'co',
  // Chile
  'Primera División de Chile': 'cl',
  'Primera B': 'cl',
  // Peru
  'Liga 1': 'pe',
  // Ecuador
  'Liga Pro': 'ec',
  // Paraguay
  'División Profesional': 'py',
  // Bolivia
  'División de Fútbol Profesional': 'bo',
  // Venezuela
  'Primera División de Venezuela': 've',
  'Liga FUTVE': 've',
  // USA
  'MLS': 'us',
  'Major League Soccer': 'us',
  // Mexico
  'Liga MX': 'mx',
  'Liga de Expansión MX': 'mx',
  // Japan
  'J1 League': 'jp',
  // South Korea
  'K League 1': 'kr',
  // Saudi Arabia
  'Saudi Pro League': 'sa',
  'Saudi Professional League': 'sa',
  // China
  'Chinese Super League': 'cn',
  // Morocco
  'Botola Pro': 'ma',
  // Egypt
  'Egyptian Premier League': 'eg',
  // South Africa
  'DStv Premiership': 'za',
  'PSL': 'za',
}
